"""
Django settings for bakery_erp project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-demo-only-change-in-production-#8dh8hxh')

DEBUG = os.getenv('DEBUG', 'True') == 'True'  # demo uchun True, deploydа False qiling

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'mybakeryerp-production.up.railway.app',
    '.railway.app',  # Barcha railway.app domenlariga ruxsat
]
CSRF_TRUSTED_ORIGINS = [
    'https://mybakeryerp-production.up.railway.app',
    'https://*.railway.app',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'whitenoise.runserver_nostatic',
    'whitenoise',

    # Custom apps
    'core',
    'production',
    'sales',
    'branches',
    'accounting',
    'hr',
    'enrollment',
    'students',
    'callcenter',
    # 'rosetta',  # requires django-rosetta
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bakery_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'bakery_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('uz', _('Uzbek (Latin)')),
    ('uz-cyrl', _('Uzbek (Kirill)')),
    ('ru', _('Russian')),
]

LANGUAGE_CODE = 'uz'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Twilio — Call Centre
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_API_KEY = os.getenv('TWILIO_API_KEY', '')
TWILIO_API_SECRET = os.getenv('TWILIO_API_SECRET', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')
CALL_CENTER_AGENT_NUMBER = os.getenv('CALL_CENTER_AGENT_NUMBER', '')

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Meta Webhook
META_VERIFY_TOKEN = os.getenv('META_VERIFY_TOKEN', '')
META_APP_SECRET = os.getenv('META_APP_SECRET', '')
META_ACCESS_TOKEN = os.getenv('META_ACCESS_TOKEN', '')
META_GRAPH_API_VERSION = os.getenv('META_GRAPH_API_VERSION', 'v21.0')
META_LEAD_DEFAULT_FORM_ID = os.getenv('META_LEAD_DEFAULT_FORM_ID', '')
META_LEAD_FETCH_ENABLED = os.getenv('META_LEAD_FETCH_ENABLED', 'False') == 'True'  # True -> webhook событие подтягивает full lead через Graph API
META_LEAD_AUTO_ASSIGN_FIRST_AGENT = os.getenv('META_LEAD_AUTO_ASSIGN_FIRST_AGENT', 'True') == 'True'  # Автоназначение первого доступного агента
META_LEAD_WEBHOOK_SIGNATURE_CHECK = os.getenv('META_LEAD_WEBHOOK_SIGNATURE_CHECK', 'False') == 'True'  # Проверка X-Hub-Signature-256 (рекомендуется в проде)  # noqa: E501
META_LEAD_ALLOWED_FORM_IDS = [x.strip() for x in os.getenv('META_LEAD_ALLOWED_FORM_IDS', '').split(',') if x.strip()]  # Белый список form_id через запятую; пусто = все формы  # noqa: E501
META_LEAD_MAP_PHONE_FIELDS = [x.strip() for x in os.getenv('META_LEAD_MAP_PHONE_FIELDS', 'phone_number,phone,mobile_number').split(',') if x.strip()]  # noqa: E501
META_LEAD_MAP_EMAIL_FIELDS = [x.strip() for x in os.getenv('META_LEAD_MAP_EMAIL_FIELDS', 'email').split(',') if x.strip()]
META_LEAD_MAP_PARENT_FIRST_FIELDS = [x.strip() for x in os.getenv('META_LEAD_MAP_PARENT_FIRST_FIELDS', 'first_name,full_name').split(',') if x.strip()]  # noqa: E501
META_LEAD_MAP_PARENT_LAST_FIELDS = [x.strip() for x in os.getenv('META_LEAD_MAP_PARENT_LAST_FIELDS', 'last_name').split(',') if x.strip()]
META_LEAD_MAP_CHILD_NAME_FIELDS = [x.strip() for x in os.getenv('META_LEAD_MAP_CHILD_NAME_FIELDS', 'child_name,student_name').split(',') if x.strip()]  # noqa: E501
META_LEAD_MAP_GRADE_FIELDS = [x.strip() for x in os.getenv('META_LEAD_MAP_GRADE_FIELDS', 'grade,class').split(',') if x.strip()]  # noqa: E501
META_LEAD_MAP_NOTES_FIELDS = [x.strip() for x in os.getenv('META_LEAD_MAP_NOTES_FIELDS', 'message,notes,comment').split(',') if x.strip()]  # noqa: E501
META_LEAD_CREATE_APPLICATION = os.getenv('META_LEAD_CREATE_APPLICATION', 'False') == 'True'  # Создавать черновик заявки автоматически
META_LEAD_DRY_RUN = os.getenv('META_LEAD_DRY_RUN', 'False') == 'True'  # Не писать в БД, только лог/ответ (для теста интеграции)  # noqa: E501
META_LEAD_DUPLICATE_WINDOW_MINUTES = int(os.getenv('META_LEAD_DUPLICATE_WINDOW_MINUTES', '60'))  # Окно дедупликации лида по телефону/ID  # noqa: E501
META_LEAD_TIMEZONE = os.getenv('META_LEAD_TIMEZONE', 'Asia/Tashkent')  # Временная зона логирования webhook
META_LEAD_SAVE_RAW_PAYLOAD = os.getenv('META_LEAD_SAVE_RAW_PAYLOAD', 'False') == 'True'  # Если есть поле/модель для raw payload, сохранять
META_LEAD_ACCEPT_TEST_EVENT = os.getenv('META_LEAD_ACCEPT_TEST_EVENT', 'True') == 'True'  # Разрешать test_event_code/webhook тесты
META_LEAD_RESPONSE_VERBOSE = os.getenv('META_LEAD_RESPONSE_VERBOSE', 'False') == 'True'  # Расширенный JSON-ответ webhook (debug)  # noqa: E501
META_LEAD_RATE_LIMIT_PER_MIN = int(os.getenv('META_LEAD_RATE_LIMIT_PER_MIN', '0'))  # 0 = без лимита; можно подключить позже
META_LEAD_SOURCE_NAME = os.getenv('META_LEAD_SOURCE_NAME', 'Meta (Facebook/Instagram)')
META_LEAD_SOURCE_CODE = os.getenv('META_LEAD_SOURCE_CODE', 'meta')
META_LEAD_REQUIRED_PHONE = os.getenv('META_LEAD_REQUIRED_PHONE', 'True') == 'True'  # Без телефона лид не создаётся
META_LEAD_FALLBACK_PHONE = os.getenv('META_LEAD_FALLBACK_PHONE', '')  # Подставить, если phone отсутствует и REQUIRED_PHONE=False
META_LEAD_LOG_PREFIX = os.getenv('META_LEAD_LOG_PREFIX', '[META-LEAD]')
META_LEAD_DEBUG = os.getenv('META_LEAD_DEBUG', 'False') == 'True'  # Включить дополнительные логи в консоль
META_LEAD_ALLOWED_OBJECT = os.getenv('META_LEAD_ALLOWED_OBJECT', 'page')  # Обычно "page"
META_LEAD_VERIFY_MODE = os.getenv('META_LEAD_VERIFY_MODE', 'subscribe')  # hub.mode ожидаемое значение
META_LEAD_USE_CREATED_TIME = os.getenv('META_LEAD_USE_CREATED_TIME', 'True') == 'True'  # Брать created_time из Meta при наличии
META_LEAD_DEFAULT_LANGUAGE = os.getenv('META_LEAD_DEFAULT_LANGUAGE', 'uz')
META_LEAD_DEFAULT_COUNTRY_CODE = os.getenv('META_LEAD_DEFAULT_COUNTRY_CODE', '+998')
META_LEAD_STRIP_NON_DIGIT_PHONE = os.getenv('META_LEAD_STRIP_NON_DIGIT_PHONE', 'True') == 'True'  # Нормализация телефона
META_LEAD_ALLOW_MULTIPLE_CHANGES = os.getenv('META_LEAD_ALLOW_MULTIPLE_CHANGES', 'True') == 'True'
META_LEAD_REQUIRE_LEADGEN_ID = os.getenv('META_LEAD_REQUIRE_LEADGEN_ID', 'False') == 'True'
META_LEAD_ALLOW_EMPTY_LAST_NAME = os.getenv('META_LEAD_ALLOW_EMPTY_LAST_NAME', 'True') == 'True'
META_LEAD_DEFAULT_LAST_NAME = os.getenv('META_LEAD_DEFAULT_LAST_NAME', 'Parent')
META_LEAD_DEFAULT_FIRST_NAME = os.getenv('META_LEAD_DEFAULT_FIRST_NAME', 'Lead')
META_LEAD_PARSE_FULL_NAME_SPLIT = os.getenv('META_LEAD_PARSE_FULL_NAME_SPLIT', 'True') == 'True'
META_LEAD_ASSIGN_BY_FORM_ID = os.getenv('META_LEAD_ASSIGN_BY_FORM_ID', 'False') == 'True'  # Логика маршрутизации по form_id (заготовка)
META_LEAD_FORM_ASSIGNMENTS = os.getenv('META_LEAD_FORM_ASSIGNMENTS', '')  # Формат: formA:user1,formB:user2
META_LEAD_REJECT_IF_NOT_ALLOWED_FORM = os.getenv('META_LEAD_REJECT_IF_NOT_ALLOWED_FORM', 'False') == 'True'
META_LEAD_ACCEPT_OLD_EVENTS_HOURS = int(os.getenv('META_LEAD_ACCEPT_OLD_EVENTS_HOURS', '72'))
META_LEAD_STORE_EXTERNAL_IDS = os.getenv('META_LEAD_STORE_EXTERNAL_IDS', 'True') == 'True'  # campaign_id/ad_id/form_id в notes/raw
META_LEAD_APPEND_UTM_TO_NOTES = os.getenv('META_LEAD_APPEND_UTM_TO_NOTES', 'True') == 'True'
META_LEAD_IGNORE_IF_STATUS_NOT_NEW = os.getenv('META_LEAD_IGNORE_IF_STATUS_NOT_NEW', 'False') == 'True'
META_LEAD_ASSIGN_ONLY_AVAILABLE_AGENTS = os.getenv('META_LEAD_ASSIGN_ONLY_AVAILABLE_AGENTS', 'False') == 'True'
META_LEAD_NOTIFY_NEW_LEAD = os.getenv('META_LEAD_NOTIFY_NEW_LEAD', 'False') == 'True'  # Хук под уведомления
META_LEAD_NOTIFY_CHANNEL = os.getenv('META_LEAD_NOTIFY_CHANNEL', '')  # telegram/slack/email (заготовка)
META_LEAD_IDEMPOTENCY_KEY_HEADER = os.getenv('META_LEAD_IDEMPOTENCY_KEY_HEADER', 'X-Meta-Idempotency-Key')
META_LEAD_CAPTURE_HEADERS = os.getenv('META_LEAD_CAPTURE_HEADERS', 'False') == 'True'  # Сохранять заголовки webhook (debug)  # noqa: E501
META_LEAD_HTTP_TIMEOUT = int(os.getenv('META_LEAD_HTTP_TIMEOUT', '15'))
META_LEAD_HTTP_RETRIES = int(os.getenv('META_LEAD_HTTP_RETRIES', '2'))
META_LEAD_MASK_PHONE_IN_LOGS = os.getenv('META_LEAD_MASK_PHONE_IN_LOGS', 'True') == 'True'
META_LEAD_MASK_EMAIL_IN_LOGS = os.getenv('META_LEAD_MASK_EMAIL_IN_LOGS', 'True') == 'True'
META_LEAD_ALLOW_GET_CHALLENGE = os.getenv('META_LEAD_ALLOW_GET_CHALLENGE', 'True') == 'True'  # Подтверждение webhook
META_LEAD_WEBHOOK_PATH = os.getenv('META_LEAD_WEBHOOK_PATH', '/enrollment/webhook/meta-lead/')
META_LEAD_SUCCESS_HTTP_CODE = int(os.getenv('META_LEAD_SUCCESS_HTTP_CODE', '200'))
META_LEAD_FAIL_HTTP_CODE = int(os.getenv('META_LEAD_FAIL_HTTP_CODE', '400'))
META_LEAD_UNKNOWN_EVENT_HTTP_CODE = int(os.getenv('META_LEAD_UNKNOWN_EVENT_HTTP_CODE', '200'))
META_LEAD_SAVE_FORM_NAME = os.getenv('META_LEAD_SAVE_FORM_NAME', 'True') == 'True'
META_LEAD_ENABLE_TEST_ENDPOINT = os.getenv('META_LEAD_ENABLE_TEST_ENDPOINT', 'False') == 'True'
META_LEAD_STRICT_MODE = os.getenv('META_LEAD_STRICT_MODE', 'False') == 'True'  # Строгая валидация всех входных полей
META_LEAD_IMPORT_BATCH_SIZE = int(os.getenv('META_LEAD_IMPORT_BATCH_SIZE', '50'))
META_LEAD_ALLOW_SOURCE_OVERRIDE = os.getenv('META_LEAD_ALLOW_SOURCE_OVERRIDE', 'False') == 'True'
META_LEAD_ALLOWED_IPS = [x.strip() for x in os.getenv('META_LEAD_ALLOWED_IPS', '').split(',') if x.strip()]  # Пусто = без whitelist
META_LEAD_QUEUE_ENABLED = os.getenv('META_LEAD_QUEUE_ENABLED', 'False') == 'True'  # Если подключите celery/rq
META_LEAD_QUEUE_NAME = os.getenv('META_LEAD_QUEUE_NAME', 'meta_leads')
META_LEAD_ENABLE_AUDIT_LOG = os.getenv('META_LEAD_ENABLE_AUDIT_LOG', 'False') == 'True'
META_LEAD_AUDIT_RETENTION_DAYS = int(os.getenv('META_LEAD_AUDIT_RETENTION_DAYS', '30'))
META_LEAD_CREATE_FOLLOWUP_TASK = os.getenv('META_LEAD_CREATE_FOLLOWUP_TASK', 'False') == 'True'  # Заготовка под задачи
META_LEAD_FOLLOWUP_DUE_MINUTES = int(os.getenv('META_LEAD_FOLLOWUP_DUE_MINUTES', '30'))
META_LEAD_CALL_AUTOCREATE = os.getenv('META_LEAD_CALL_AUTOCREATE', 'False') == 'True'  # Создавать CallRecord в статусе ringing сразу
META_LEAD_CALL_AUTODIAL = os.getenv('META_LEAD_CALL_AUTODIAL', 'False') == 'True'  # Автодозвон (рекомендуется выключить)
META_LEAD_BLOCKED_PHONES = [x.strip() for x in os.getenv('META_LEAD_BLOCKED_PHONES', '').split(',') if x.strip()]  # Черный список
META_LEAD_BLOCKED_EMAILS = [x.strip().lower() for x in os.getenv('META_LEAD_BLOCKED_EMAILS', '').split(',') if x.strip()]
META_LEAD_MIN_PHONE_LENGTH = int(os.getenv('META_LEAD_MIN_PHONE_LENGTH', '7'))
META_LEAD_MAX_PHONE_LENGTH = int(os.getenv('META_LEAD_MAX_PHONE_LENGTH', '15'))
META_LEAD_SAFE_MODE = os.getenv('META_LEAD_SAFE_MODE', 'True') == 'True'  # Не падать по исключениям, отвечать OK и логировать
META_LEAD_USE_HTTPS_ONLY = os.getenv('META_LEAD_USE_HTTPS_ONLY', 'False') == 'True'  # Проверка scheme
META_LEAD_REQUIRE_USER_AGENT = os.getenv('META_LEAD_REQUIRE_USER_AGENT', 'False') == 'True'
META_LEAD_ALLOWED_USER_AGENTS = [x.strip() for x in os.getenv('META_LEAD_ALLOWED_USER_AGENTS', '').split(',') if x.strip()]  # Опционально
META_LEAD_HMAC_ALGO = os.getenv('META_LEAD_HMAC_ALGO', 'sha256')
META_LEAD_SIGNATURE_HEADER = os.getenv('META_LEAD_SIGNATURE_HEADER', 'X-Hub-Signature-256')
META_LEAD_EVENT_FIELD = os.getenv('META_LEAD_EVENT_FIELD', 'leadgen')
META_LEAD_FORCE_SOURCE_META = os.getenv('META_LEAD_FORCE_SOURCE_META', 'True') == 'True'
META_LEAD_ENRICH_WITH_AD_OBJECT = os.getenv('META_LEAD_ENRICH_WITH_AD_OBJECT', 'False') == 'True'
META_LEAD_TAGS = [x.strip() for x in os.getenv('META_LEAD_TAGS', 'meta,ad').split(',') if x.strip()]
META_LEAD_POST_SAVE_HOOK = os.getenv('META_LEAD_POST_SAVE_HOOK', '')  # dotted path callable (заготовка)
META_LEAD_PRE_SAVE_HOOK = os.getenv('META_LEAD_PRE_SAVE_HOOK', '')
META_LEAD_MONITORING_ENABLED = os.getenv('META_LEAD_MONITORING_ENABLED', 'False') == 'True'
META_LEAD_MONITORING_NAMESPACE = os.getenv('META_LEAD_MONITORING_NAMESPACE', 'enrollment.meta')
META_LEAD_SANITIZE_NOTES = os.getenv('META_LEAD_SANITIZE_NOTES', 'True') == 'True'
META_LEAD_TRUNCATE_NOTES_LENGTH = int(os.getenv('META_LEAD_TRUNCATE_NOTES_LENGTH', '5000'))
META_LEAD_SAVE_RAW_TO_FILE = os.getenv('META_LEAD_SAVE_RAW_TO_FILE', 'False') == 'True'
META_LEAD_RAW_FILE_DIR = os.getenv('META_LEAD_RAW_FILE_DIR', '')
META_LEAD_ENABLE_REPLAY_PROTECTION = os.getenv('META_LEAD_ENABLE_REPLAY_PROTECTION', 'False') == 'True'
META_LEAD_REPLAY_WINDOW_SECONDS = int(os.getenv('META_LEAD_REPLAY_WINDOW_SECONDS', '300'))
META_LEAD_MAX_PAYLOAD_SIZE_KB = int(os.getenv('META_LEAD_MAX_PAYLOAD_SIZE_KB', '512'))
META_LEAD_REQUIRE_CONTENT_TYPE_JSON = os.getenv('META_LEAD_REQUIRE_CONTENT_TYPE_JSON', 'True') == 'True'
META_LEAD_ALLOWED_METHODS = [x.strip().upper() for x in os.getenv('META_LEAD_ALLOWED_METHODS', 'GET,POST').split(',') if x.strip()]
META_LEAD_ENABLE_HEALTHCHECK = os.getenv('META_LEAD_ENABLE_HEALTHCHECK', 'False') == 'True'
META_LEAD_HEALTHCHECK_PATH = os.getenv('META_LEAD_HEALTHCHECK_PATH', '/enrollment/webhook/meta-lead/health/')
META_LEAD_STORE_LAST_EVENT_TS = os.getenv('META_LEAD_STORE_LAST_EVENT_TS', 'False') == 'True'
META_LEAD_AUTOCLOSE_DUPLICATES = os.getenv('META_LEAD_AUTOCLOSE_DUPLICATES', 'False') == 'True'
META_LEAD_DUPLICATE_STATUS = os.getenv('META_LEAD_DUPLICATE_STATUS', 'declined')
META_LEAD_ALLOW_MANUAL_SOURCE = os.getenv('META_LEAD_ALLOW_MANUAL_SOURCE', 'True') == 'True'
META_LEAD_DEFAULT_STATUS = os.getenv('META_LEAD_DEFAULT_STATUS', 'new')
META_LEAD_ON_ERROR_STATUS = os.getenv('META_LEAD_ON_ERROR_STATUS', 'new')
META_LEAD_ENABLE_METRICS_LOG = os.getenv('META_LEAD_ENABLE_METRICS_LOG', 'False') == 'True'
META_LEAD_LOG_JSON = os.getenv('META_LEAD_LOG_JSON', 'False') == 'True'
META_LEAD_LOG_LEVEL = os.getenv('META_LEAD_LOG_LEVEL', 'INFO')
META_LEAD_RESERVED_01 = os.getenv('META_LEAD_RESERVED_01', '')
META_LEAD_RESERVED_02 = os.getenv('META_LEAD_RESERVED_02', '')
META_LEAD_RESERVED_03 = os.getenv('META_LEAD_RESERVED_03', '')
META_LEAD_RESERVED_04 = os.getenv('META_LEAD_RESERVED_04', '')
META_LEAD_RESERVED_05 = os.getenv('META_LEAD_RESERVED_05', '')
META_LEAD_RESERVED_06 = os.getenv('META_LEAD_RESERVED_06', '')
META_LEAD_RESERVED_07 = os.getenv('META_LEAD_RESERVED_07', '')
META_LEAD_RESERVED_08 = os.getenv('META_LEAD_RESERVED_08', '')
META_LEAD_RESERVED_09 = os.getenv('META_LEAD_RESERVED_09', '')
META_LEAD_RESERVED_10 = os.getenv('META_LEAD_RESERVED_10', '')
META_LEAD_RESERVED_11 = os.getenv('META_LEAD_RESERVED_11', '')
META_LEAD_RESERVED_12 = os.getenv('META_LEAD_RESERVED_12', '')
META_LEAD_RESERVED_13 = os.getenv('META_LEAD_RESERVED_13', '')
META_LEAD_RESERVED_14 = os.getenv('META_LEAD_RESERVED_14', '')
META_LEAD_RESERVED_15 = os.getenv('META_LEAD_RESERVED_15', '')
META_LEAD_RESERVED_16 = os.getenv('META_LEAD_RESERVED_16', '')
META_LEAD_RESERVED_17 = os.getenv('META_LEAD_RESERVED_17', '')
META_LEAD_RESERVED_18 = os.getenv('META_LEAD_RESERVED_18', '')
META_LEAD_RESERVED_19 = os.getenv('META_LEAD_RESERVED_19', '')
META_LEAD_RESERVED_20 = os.getenv('META_LEAD_RESERVED_20', '')
META_LEAD_RESERVED_21 = os.getenv('META_LEAD_RESERVED_21', '')
META_LEAD_RESERVED_22 = os.getenv('META_LEAD_RESERVED_22', '')
META_LEAD_RESERVED_23 = os.getenv('META_LEAD_RESERVED_23', '')
META_LEAD_RESERVED_24 = os.getenv('META_LEAD_RESERVED_24', '')
META_LEAD_RESERVED_25 = os.getenv('META_LEAD_RESERVED_25', '')
META_LEAD_RESERVED_26 = os.getenv('META_LEAD_RESERVED_26', '')
META_LEAD_RESERVED_27 = os.getenv('META_LEAD_RESERVED_27', '')
META_LEAD_RESERVED_28 = os.getenv('META_LEAD_RESERVED_28', '')
META_LEAD_RESERVED_29 = os.getenv('META_LEAD_RESERVED_29', '')
META_LEAD_RESERVED_30 = os.getenv('META_LEAD_RESERVED_30', '')
META_LEAD_RESERVED_31 = os.getenv('META_LEAD_RESERVED_31', '')
META_LEAD_RESERVED_32 = os.getenv('META_LEAD_RESERVED_32', '')
META_LEAD_RESERVED_33 = os.getenv('META_LEAD_RESERVED_33', '')
META_LEAD_RESERVED_34 = os.getenv('META_LEAD_RESERVED_34', '')
META_LEAD_RESERVED_35 = os.getenv('META_LEAD_RESERVED_35', '')
META_LEAD_RESERVED_36 = os.getenv('META_LEAD_RESERVED_36', '')
META_LEAD_RESERVED_37 = os.getenv('META_LEAD_RESERVED_37', '')
META_LEAD_RESERVED_38 = os.getenv('META_LEAD_RESERVED_38', '')
META_LEAD_RESERVED_39 = os.getenv('META_LEAD_RESERVED_39', '')
META_LEAD_RESERVED_40 = os.getenv('META_LEAD_RESERVED_40', '')
META_LEAD_RESERVED_41 = os.getenv('META_LEAD_RESERVED_41', '')
META_LEAD_RESERVED_42 = os.getenv('META_LEAD_RESERVED_42', '')
META_LEAD_RESERVED_43 = os.getenv('META_LEAD_RESERVED_43', '')
META_LEAD_RESERVED_44 = os.getenv('META_LEAD_RESERVED_44', '')
META_LEAD_RESERVED_45 = os.getenv('META_LEAD_RESERVED_45', '')
META_LEAD_RESERVED_46 = os.getenv('META_LEAD_RESERVED_46', '')
META_LEAD_RESERVED_47 = os.getenv('META_LEAD_RESERVED_47', '')
META_LEAD_RESERVED_48 = os.getenv('META_LEAD_RESERVED_48', '')
META_LEAD_RESERVED_49 = os.getenv('META_LEAD_RESERVED_49', '')
META_LEAD_RESERVED_50 = os.getenv('META_LEAD_RESERVED_50', '')
META_LEAD_RESERVED_51 = os.getenv('META_LEAD_RESERVED_51', '')
META_LEAD_RESERVED_52 = os.getenv('META_LEAD_RESERVED_52', '')
META_LEAD_RESERVED_53 = os.getenv('META_LEAD_RESERVED_53', '')
META_LEAD_RESERVED_54 = os.getenv('META_LEAD_RESERVED_54', '')
META_LEAD_RESERVED_55 = os.getenv('META_LEAD_RESERVED_55', '')
META_LEAD_RESERVED_56 = os.getenv('META_LEAD_RESERVED_56', '')
META_LEAD_RESERVED_57 = os.getenv('META_LEAD_RESERVED_57', '')
META_LEAD_RESERVED_58 = os.getenv('META_LEAD_RESERVED_58', '')
META_LEAD_RESERVED_59 = os.getenv('META_LEAD_RESERVED_59', '')
META_LEAD_RESERVED_60 = os.getenv('META_LEAD_RESERVED_60', '')
META_LEAD_RESERVED_61 = os.getenv('META_LEAD_RESERVED_61', '')
META_LEAD_RESERVED_62 = os.getenv('META_LEAD_RESERVED_62', '')
META_LEAD_RESERVED_63 = os.getenv('META_LEAD_RESERVED_63', '')
META_LEAD_RESERVED_64 = os.getenv('META_LEAD_RESERVED_64', '')
META_LEAD_RESERVED_65 = os.getenv('META_LEAD_RESERVED_65', '')
META_LEAD_RESERVED_66 = os.getenv('META_LEAD_RESERVED_66', '')
META_LEAD_RESERVED_67 = os.getenv('META_LEAD_RESERVED_67', '')
META_LEAD_RESERVED_68 = os.getenv('META_LEAD_RESERVED_68', '')
META_LEAD_RESERVED_69 = os.getenv('META_LEAD_RESERVED_69', '')
META_LEAD_RESERVED_70 = os.getenv('META_LEAD_RESERVED_70', '')
META_LEAD_RESERVED_71 = os.getenv('META_LEAD_RESERVED_71', '')
META_LEAD_RESERVED_72 = os.getenv('META_LEAD_RESERVED_72', '')
META_LEAD_RESERVED_73 = os.getenv('META_LEAD_RESERVED_73', '')
META_LEAD_RESERVED_74 = os.getenv('META_LEAD_RESERVED_74', '')
META_LEAD_RESERVED_75 = os.getenv('META_LEAD_RESERVED_75', '')
META_LEAD_RESERVED_76 = os.getenv('META_LEAD_RESERVED_76', '')
META_LEAD_RESERVED_77 = os.getenv('META_LEAD_RESERVED_77', '')
META_LEAD_RESERVED_78 = os.getenv('META_LEAD_RESERVED_78', '')
META_LEAD_RESERVED_79 = os.getenv('META_LEAD_RESERVED_79', '')
META_LEAD_RESERVED_80 = os.getenv('META_LEAD_RESERVED_80', '')
META_LEAD_RESERVED_81 = os.getenv('META_LEAD_RESERVED_81', '')
META_LEAD_RESERVED_82 = os.getenv('META_LEAD_RESERVED_82', '')
META_LEAD_RESERVED_83 = os.getenv('META_LEAD_RESERVED_83', '')
META_LEAD_RESERVED_84 = os.getenv('META_LEAD_RESERVED_84', '')
META_LEAD_RESERVED_85 = os.getenv('META_LEAD_RESERVED_85', '')
META_LEAD_RESERVED_86 = os.getenv('META_LEAD_RESERVED_86', '')
META_LEAD_RESERVED_87 = os.getenv('META_LEAD_RESERVED_87', '')
META_LEAD_RESERVED_88 = os.getenv('META_LEAD_RESERVED_88', '')
META_LEAD_RESERVED_89 = os.getenv('META_LEAD_RESERVED_89', '')
META_LEAD_RESERVED_90 = os.getenv('META_LEAD_RESERVED_90', '')
META_LEAD_RESERVED_91 = os.getenv('META_LEAD_RESERVED_91', '')
META_LEAD_RESERVED_92 = os.getenv('META_LEAD_RESERVED_92', '')
META_LEAD_RESERVED_93 = os.getenv('META_LEAD_RESERVED_93', '')
META_LEAD_RESERVED_94 = os.getenv('META_LEAD_RESERVED_94', '')
META_LEAD_RESERVED_95 = os.getenv('META_LEAD_RESERVED_95', '')
META_LEAD_RESERVED_96 = os.getenv('META_LEAD_RESERVED_96', '')
META_LEAD_RESERVED_97 = os.getenv('META_LEAD_RESERVED_97', '')
META_LEAD_RESERVED_98 = os.getenv('META_LEAD_RESERVED_98', '')
META_LEAD_RESERVED_99 = os.getenv('META_LEAD_RESERVED_99', '')
META_LEAD_RESERVED_100 = os.getenv('META_LEAD_RESERVED_100', '')

# Параметры внутреннего SIP/мобильного колл-центра
CALL_CENTER_ENABLE_SIP = os.getenv('CALL_CENTER_ENABLE_SIP', 'False') == 'True'
CALL_CENTER_SIP_DOMAIN = os.getenv('CALL_CENTER_SIP_DOMAIN', '')
CALL_CENTER_SIP_USERNAME = os.getenv('CALL_CENTER_SIP_USERNAME', '')
CALL_CENTER_SIP_PASSWORD = os.getenv('CALL_CENTER_SIP_PASSWORD', '')
CALL_CENTER_QUEUE_NAME = os.getenv('CALL_CENTER_QUEUE_NAME', 'admissions')
CALL_CENTER_MAX_RING_SECONDS = int(os.getenv('CALL_CENTER_MAX_RING_SECONDS', '20'))
CALL_CENTER_RECORDING_CHANNEL = os.getenv('CALL_CENTER_RECORDING_CHANNEL', 'dual')
CALL_CENTER_RECORDING_TRIM = os.getenv('CALL_CENTER_RECORDING_TRIM', 'trim-silence')
CALL_CENTER_RECORDING_STATUS_EVENTS = [x.strip() for x in os.getenv('CALL_CENTER_RECORDING_STATUS_EVENTS', 'in-progress,completed,absent').split(',') if x.strip()]  # noqa: E501
CALL_CENTER_STATUS_CALLBACK_EVENTS = [x.strip() for x in os.getenv('CALL_CENTER_STATUS_CALLBACK_EVENTS', 'initiated,ringing,answered,completed').split(',') if x.strip()]  # noqa: E501
CALL_CENTER_ENABLE_CONFERENCE = os.getenv('CALL_CENTER_ENABLE_CONFERENCE', 'False') == 'True'
CALL_CENTER_ENABLE_WARM_TRANSFER = os.getenv('CALL_CENTER_ENABLE_WARM_TRANSFER', 'False') == 'True'
CALL_CENTER_ENABLE_HOLD_MUSIC = os.getenv('CALL_CENTER_ENABLE_HOLD_MUSIC', 'False') == 'True'
CALL_CENTER_HOLD_MUSIC_URL = os.getenv('CALL_CENTER_HOLD_MUSIC_URL', '')
CALL_CENTER_ENABLE_AGENT_PIN = os.getenv('CALL_CENTER_ENABLE_AGENT_PIN', 'False') == 'True'
CALL_CENTER_AGENT_PIN_LENGTH = int(os.getenv('CALL_CENTER_AGENT_PIN_LENGTH', '4'))
CALL_CENTER_ENABLE_CALL_NOTES_REQUIRED = os.getenv('CALL_CENTER_ENABLE_CALL_NOTES_REQUIRED', 'False') == 'True'
CALL_CENTER_AUTO_ASSIGN_LEAD_ON_CALL = os.getenv('CALL_CENTER_AUTO_ASSIGN_LEAD_ON_CALL', 'True') == 'True'
CALL_CENTER_DEFAULT_COUNTRY_CODE = os.getenv('CALL_CENTER_DEFAULT_COUNTRY_CODE', '+998')
CALL_CENTER_SANITIZE_PHONE = os.getenv('CALL_CENTER_SANITIZE_PHONE', 'True') == 'True'
CALL_CENTER_RATE_LIMIT_DIAL_PER_MIN = int(os.getenv('CALL_CENTER_RATE_LIMIT_DIAL_PER_MIN', '0'))
CALL_CENTER_ALLOW_INBOUND = os.getenv('CALL_CENTER_ALLOW_INBOUND', 'True') == 'True'
CALL_CENTER_ALLOW_OUTBOUND = os.getenv('CALL_CENTER_ALLOW_OUTBOUND', 'True') == 'True'
CALL_CENTER_ALLOWED_AGENT_GROUPS = [x.strip() for x in os.getenv('CALL_CENTER_ALLOWED_AGENT_GROUPS', 'enrollment_agent,enrollment_manager').split(',') if x.strip()]  # noqa: E501
CALL_CENTER_ENFORCE_BUSINESS_HOURS = os.getenv('CALL_CENTER_ENFORCE_BUSINESS_HOURS', 'False') == 'True'
CALL_CENTER_BUSINESS_HOUR_START = os.getenv('CALL_CENTER_BUSINESS_HOUR_START', '08:00')
CALL_CENTER_BUSINESS_HOUR_END = os.getenv('CALL_CENTER_BUSINESS_HOUR_END', '20:00')
CALL_CENTER_TIMEZONE = os.getenv('CALL_CENTER_TIMEZONE', 'Asia/Tashkent')
CALL_CENTER_RECORDING_REQUIRED = os.getenv('CALL_CENTER_RECORDING_REQUIRED', 'True') == 'True'
CALL_CENTER_RECORDING_ENCRYPTED = os.getenv('CALL_CENTER_RECORDING_ENCRYPTED', 'False') == 'True'
CALL_CENTER_KEEP_RECORDING_DAYS = int(os.getenv('CALL_CENTER_KEEP_RECORDING_DAYS', '365'))
CALL_CENTER_BLOCKLIST_NUMBERS = [x.strip() for x in os.getenv('CALL_CENTER_BLOCKLIST_NUMBERS', '').split(',') if x.strip()]
CALL_CENTER_ALLOWLIST_PREFIXES = [x.strip() for x in os.getenv('CALL_CENTER_ALLOWLIST_PREFIXES', '').split(',') if x.strip()]
CALL_CENTER_DIAL_TIMEOUT_SECONDS = int(os.getenv('CALL_CENTER_DIAL_TIMEOUT_SECONDS', '30'))
CALL_CENTER_RETRY_ON_BUSY = os.getenv('CALL_CENTER_RETRY_ON_BUSY', 'False') == 'True'
CALL_CENTER_RETRY_COUNT = int(os.getenv('CALL_CENTER_RETRY_COUNT', '0'))
CALL_CENTER_RETRY_DELAY_SECONDS = int(os.getenv('CALL_CENTER_RETRY_DELAY_SECONDS', '60'))
CALL_CENTER_ENABLE_VOICEMAIL = os.getenv('CALL_CENTER_ENABLE_VOICEMAIL', 'False') == 'True'
CALL_CENTER_VOICEMAIL_MAX_LENGTH = int(os.getenv('CALL_CENTER_VOICEMAIL_MAX_LENGTH', '120'))
CALL_CENTER_REQUIRE_LEAD_FOR_OUTBOUND = os.getenv('CALL_CENTER_REQUIRE_LEAD_FOR_OUTBOUND', 'False') == 'True'
CALL_CENTER_DEFAULT_OUTBOUND_CALLER_ID = os.getenv('CALL_CENTER_DEFAULT_OUTBOUND_CALLER_ID', '')
CALL_CENTER_MASK_NUMBERS_IN_UI = os.getenv('CALL_CENTER_MASK_NUMBERS_IN_UI', 'False') == 'True'
CALL_CENTER_LOG_WEBHOOK_PAYLOAD = os.getenv('CALL_CENTER_LOG_WEBHOOK_PAYLOAD', 'False') == 'True'
CALL_CENTER_LOG_LEVEL = os.getenv('CALL_CENTER_LOG_LEVEL', 'INFO')
CALL_CENTER_ENABLE_METRICS = os.getenv('CALL_CENTER_ENABLE_METRICS', 'False') == 'True'
CALL_CENTER_METRICS_NAMESPACE = os.getenv('CALL_CENTER_METRICS_NAMESPACE', 'enrollment.calls')
CALL_CENTER_ENABLE_AGENT_PRESENCE = os.getenv('CALL_CENTER_ENABLE_AGENT_PRESENCE', 'True') == 'True'
CALL_CENTER_ENABLE_AUTO_WRAPUP = os.getenv('CALL_CENTER_ENABLE_AUTO_WRAPUP', 'False') == 'True'
CALL_CENTER_WRAPUP_SECONDS = int(os.getenv('CALL_CENTER_WRAPUP_SECONDS', '15'))
CALL_CENTER_ENABLE_DISPOSITION_CODES = os.getenv('CALL_CENTER_ENABLE_DISPOSITION_CODES', 'False') == 'True'
CALL_CENTER_DISPOSITION_CODES = [x.strip() for x in os.getenv('CALL_CENTER_DISPOSITION_CODES', 'answered,no_answer,busy,wrong_number,interested,not_interested,callback').split(',') if x.strip()]  # noqa: E501
CALL_CENTER_REQUIRE_DISPOSITION = os.getenv('CALL_CENTER_REQUIRE_DISPOSITION', 'False') == 'True'
CALL_CENTER_ENABLE_CALLBACK_SCHEDULER = os.getenv('CALL_CENTER_ENABLE_CALLBACK_SCHEDULER', 'False') == 'True'
CALL_CENTER_MAX_CONCURRENT_CALLS_PER_AGENT = int(os.getenv('CALL_CENTER_MAX_CONCURRENT_CALLS_PER_AGENT', '1'))
CALL_CENTER_AGENT_HEARTBEAT_SECONDS = int(os.getenv('CALL_CENTER_AGENT_HEARTBEAT_SECONDS', '30'))
CALL_CENTER_INBOUND_GREETING_VOICE = os.getenv('CALL_CENTER_INBOUND_GREETING_VOICE', 'alice')
CALL_CENTER_INBOUND_GREETING_LANG = os.getenv('CALL_CENTER_INBOUND_GREETING_LANG', 'uz-UZ')
CALL_CENTER_INBOUND_GREETING_TEXT = os.getenv('CALL_CENTER_INBOUND_GREETING_TEXT', "Bunyod Non Sharjah School qabul bo'limiga xush kelibsiz")
CALL_CENTER_ENABLE_IVR = os.getenv('CALL_CENTER_ENABLE_IVR', 'False') == 'True'
CALL_CENTER_IVR_TIMEOUT = int(os.getenv('CALL_CENTER_IVR_TIMEOUT', '5'))
CALL_CENTER_IVR_DIGITS = os.getenv('CALL_CENTER_IVR_DIGITS', '1')
CALL_CENTER_IVR_ROUTE_MAP = os.getenv('CALL_CENTER_IVR_ROUTE_MAP', '1:admissions')
CALL_CENTER_ALLOW_MANUAL_CALL_RECORD_UPLOAD = os.getenv('CALL_CENTER_ALLOW_MANUAL_CALL_RECORD_UPLOAD', 'False') == 'True'
CALL_CENTER_ENABLE_WEBRTC = os.getenv('CALL_CENTER_ENABLE_WEBRTC', 'False') == 'True'
CALL_CENTER_WEBRTC_APP_NAME = os.getenv('CALL_CENTER_WEBRTC_APP_NAME', 'BunyodSchoolCallCenter')
CALL_CENTER_ENABLE_AGENT_CALL_BARGE = os.getenv('CALL_CENTER_ENABLE_AGENT_CALL_BARGE', 'False') == 'True'
CALL_CENTER_ENABLE_AGENT_WHISPER = os.getenv('CALL_CENTER_ENABLE_AGENT_WHISPER', 'False') == 'True'
CALL_CENTER_ENABLE_SUPERVISOR = os.getenv('CALL_CENTER_ENABLE_SUPERVISOR', 'False') == 'True'
CALL_CENTER_SUPERVISOR_GROUP = os.getenv('CALL_CENTER_SUPERVISOR_GROUP', 'enrollment_manager')
CALL_CENTER_ENABLE_RECORDING_TRANSCRIPT = os.getenv('CALL_CENTER_ENABLE_RECORDING_TRANSCRIPT', 'False') == 'True'
CALL_CENTER_TRANSCRIPT_PROVIDER = os.getenv('CALL_CENTER_TRANSCRIPT_PROVIDER', '')
CALL_CENTER_TRANSCRIPT_LANGUAGE = os.getenv('CALL_CENTER_TRANSCRIPT_LANGUAGE', 'uz')
CALL_CENTER_ENABLE_SENTIMENT = os.getenv('CALL_CENTER_ENABLE_SENTIMENT', 'False') == 'True'
CALL_CENTER_EXPORT_CSV = os.getenv('CALL_CENTER_EXPORT_CSV', 'True') == 'True'
CALL_CENTER_EXPORT_XLSX = os.getenv('CALL_CENTER_EXPORT_XLSX', 'True') == 'True'
CALL_CENTER_ENABLE_AUDIT_LOG = os.getenv('CALL_CENTER_ENABLE_AUDIT_LOG', 'False') == 'True'
CALL_CENTER_AUDIT_RETENTION_DAYS = int(os.getenv('CALL_CENTER_AUDIT_RETENTION_DAYS', '30'))
CALL_CENTER_ENABLE_QUEUEING = os.getenv('CALL_CENTER_ENABLE_QUEUEING', 'False') == 'True'
CALL_CENTER_QUEUE_MAX_SIZE = int(os.getenv('CALL_CENTER_QUEUE_MAX_SIZE', '100'))
CALL_CENTER_QUEUE_STRATEGY = os.getenv('CALL_CENTER_QUEUE_STRATEGY', 'round_robin')
CALL_CENTER_ENABLE_AGENT_SKILLS = os.getenv('CALL_CENTER_ENABLE_AGENT_SKILLS', 'False') == 'True'
CALL_CENTER_AGENT_SKILLS = os.getenv('CALL_CENTER_AGENT_SKILLS', '')
CALL_CENTER_ENABLE_BLACKOUT_DATES = os.getenv('CALL_CENTER_ENABLE_BLACKOUT_DATES', 'False') == 'True'
CALL_CENTER_BLACKOUT_DATES = [x.strip() for x in os.getenv('CALL_CENTER_BLACKOUT_DATES', '').split(',') if x.strip()]
CALL_CENTER_ENABLE_SMS_FALLBACK = os.getenv('CALL_CENTER_ENABLE_SMS_FALLBACK', 'False') == 'True'
CALL_CENTER_SMS_TEMPLATE = os.getenv('CALL_CENTER_SMS_TEMPLATE', '')
CALL_CENTER_ENABLE_EMAIL_FALLBACK = os.getenv('CALL_CENTER_ENABLE_EMAIL_FALLBACK', 'False') == 'True'
CALL_CENTER_EMAIL_TEMPLATE = os.getenv('CALL_CENTER_EMAIL_TEMPLATE', '')
CALL_CENTER_RESERVED_01 = os.getenv('CALL_CENTER_RESERVED_01', '')
CALL_CENTER_RESERVED_02 = os.getenv('CALL_CENTER_RESERVED_02', '')
CALL_CENTER_RESERVED_03 = os.getenv('CALL_CENTER_RESERVED_03', '')
CALL_CENTER_RESERVED_04 = os.getenv('CALL_CENTER_RESERVED_04', '')
CALL_CENTER_RESERVED_05 = os.getenv('CALL_CENTER_RESERVED_05', '')
CALL_CENTER_RESERVED_06 = os.getenv('CALL_CENTER_RESERVED_06', '')
CALL_CENTER_RESERVED_07 = os.getenv('CALL_CENTER_RESERVED_07', '')
CALL_CENTER_RESERVED_08 = os.getenv('CALL_CENTER_RESERVED_08', '')
CALL_CENTER_RESERVED_09 = os.getenv('CALL_CENTER_RESERVED_09', '')
CALL_CENTER_RESERVED_10 = os.getenv('CALL_CENTER_RESERVED_10', '')
CALL_CENTER_RESERVED_11 = os.getenv('CALL_CENTER_RESERVED_11', '')
CALL_CENTER_RESERVED_12 = os.getenv('CALL_CENTER_RESERVED_12', '')
CALL_CENTER_RESERVED_13 = os.getenv('CALL_CENTER_RESERVED_13', '')
CALL_CENTER_RESERVED_14 = os.getenv('CALL_CENTER_RESERVED_14', '')
CALL_CENTER_RESERVED_15 = os.getenv('CALL_CENTER_RESERVED_15', '')
CALL_CENTER_RESERVED_16 = os.getenv('CALL_CENTER_RESERVED_16', '')
CALL_CENTER_RESERVED_17 = os.getenv('CALL_CENTER_RESERVED_17', '')
CALL_CENTER_RESERVED_18 = os.getenv('CALL_CENTER_RESERVED_18', '')
CALL_CENTER_RESERVED_19 = os.getenv('CALL_CENTER_RESERVED_19', '')
CALL_CENTER_RESERVED_20 = os.getenv('CALL_CENTER_RESERVED_20', '')
CALL_CENTER_RESERVED_21 = os.getenv('CALL_CENTER_RESERVED_21', '')
CALL_CENTER_RESERVED_22 = os.getenv('CALL_CENTER_RESERVED_22', '')
CALL_CENTER_RESERVED_23 = os.getenv('CALL_CENTER_RESERVED_23', '')
CALL_CENTER_RESERVED_24 = os.getenv('CALL_CENTER_RESERVED_24', '')
CALL_CENTER_RESERVED_25 = os.getenv('CALL_CENTER_RESERVED_25', '')
CALL_CENTER_RESERVED_26 = os.getenv('CALL_CENTER_RESERVED_26', '')
CALL_CENTER_RESERVED_27 = os.getenv('CALL_CENTER_RESERVED_27', '')
CALL_CENTER_RESERVED_28 = os.getenv('CALL_CENTER_RESERVED_28', '')
CALL_CENTER_RESERVED_29 = os.getenv('CALL_CENTER_RESERVED_29', '')
CALL_CENTER_RESERVED_30 = os.getenv('CALL_CENTER_RESERVED_30', '')
CALL_CENTER_RESERVED_31 = os.getenv('CALL_CENTER_RESERVED_31', '')
CALL_CENTER_RESERVED_32 = os.getenv('CALL_CENTER_RESERVED_32', '')
CALL_CENTER_RESERVED_33 = os.getenv('CALL_CENTER_RESERVED_33', '')
CALL_CENTER_RESERVED_34 = os.getenv('CALL_CENTER_RESERVED_34', '')
CALL_CENTER_RESERVED_35 = os.getenv('CALL_CENTER_RESERVED_35', '')
CALL_CENTER_RESERVED_36 = os.getenv('CALL_CENTER_RESERVED_36', '')
CALL_CENTER_RESERVED_37 = os.getenv('CALL_CENTER_RESERVED_37', '')
CALL_CENTER_RESERVED_38 = os.getenv('CALL_CENTER_RESERVED_38', '')
CALL_CENTER_RESERVED_39 = os.getenv('CALL_CENTER_RESERVED_39', '')
CALL_CENTER_RESERVED_40 = os.getenv('CALL_CENTER_RESERVED_40', '')
CALL_CENTER_RESERVED_41 = os.getenv('CALL_CENTER_RESERVED_41', '')
CALL_CENTER_RESERVED_42 = os.getenv('CALL_CENTER_RESERVED_42', '')
CALL_CENTER_RESERVED_43 = os.getenv('CALL_CENTER_RESERVED_43', '')
CALL_CENTER_RESERVED_44 = os.getenv('CALL_CENTER_RESERVED_44', '')
CALL_CENTER_RESERVED_45 = os.getenv('CALL_CENTER_RESERVED_45', '')
CALL_CENTER_RESERVED_46 = os.getenv('CALL_CENTER_RESERVED_46', '')
CALL_CENTER_RESERVED_47 = os.getenv('CALL_CENTER_RESERVED_47', '')
CALL_CENTER_RESERVED_48 = os.getenv('CALL_CENTER_RESERVED_48', '')
CALL_CENTER_RESERVED_49 = os.getenv('CALL_CENTER_RESERVED_49', '')
CALL_CENTER_RESERVED_50 = os.getenv('CALL_CENTER_RESERVED_50', '')
CALL_CENTER_RESERVED_51 = os.getenv('CALL_CENTER_RESERVED_51', '')
CALL_CENTER_RESERVED_52 = os.getenv('CALL_CENTER_RESERVED_52', '')
CALL_CENTER_RESERVED_53 = os.getenv('CALL_CENTER_RESERVED_53', '')
CALL_CENTER_RESERVED_54 = os.getenv('CALL_CENTER_RESERVED_54', '')
CALL_CENTER_RESERVED_55 = os.getenv('CALL_CENTER_RESERVED_55', '')
CALL_CENTER_RESERVED_56 = os.getenv('CALL_CENTER_RESERVED_56', '')
CALL_CENTER_RESERVED_57 = os.getenv('CALL_CENTER_RESERVED_57', '')
CALL_CENTER_RESERVED_58 = os.getenv('CALL_CENTER_RESERVED_58', '')
CALL_CENTER_RESERVED_59 = os.getenv('CALL_CENTER_RESERVED_59', '')
CALL_CENTER_RESERVED_60 = os.getenv('CALL_CENTER_RESERVED_60', '')
CALL_CENTER_RESERVED_61 = os.getenv('CALL_CENTER_RESERVED_61', '')
CALL_CENTER_RESERVED_62 = os.getenv('CALL_CENTER_RESERVED_62', '')
CALL_CENTER_RESERVED_63 = os.getenv('CALL_CENTER_RESERVED_63', '')
CALL_CENTER_RESERVED_64 = os.getenv('CALL_CENTER_RESERVED_64', '')
CALL_CENTER_RESERVED_65 = os.getenv('CALL_CENTER_RESERVED_65', '')
CALL_CENTER_RESERVED_66 = os.getenv('CALL_CENTER_RESERVED_66', '')
CALL_CENTER_RESERVED_67 = os.getenv('CALL_CENTER_RESERVED_67', '')
CALL_CENTER_RESERVED_68 = os.getenv('CALL_CENTER_RESERVED_68', '')
CALL_CENTER_RESERVED_69 = os.getenv('CALL_CENTER_RESERVED_69', '')
CALL_CENTER_RESERVED_70 = os.getenv('CALL_CENTER_RESERVED_70', '')
CALL_CENTER_RESERVED_71 = os.getenv('CALL_CENTER_RESERVED_71', '')
CALL_CENTER_RESERVED_72 = os.getenv('CALL_CENTER_RESERVED_72', '')
CALL_CENTER_RESERVED_73 = os.getenv('CALL_CENTER_RESERVED_73', '')
CALL_CENTER_RESERVED_74 = os.getenv('CALL_CENTER_RESERVED_74', '')
CALL_CENTER_RESERVED_75 = os.getenv('CALL_CENTER_RESERVED_75', '')
CALL_CENTER_RESERVED_76 = os.getenv('CALL_CENTER_RESERVED_76', '')
CALL_CENTER_RESERVED_77 = os.getenv('CALL_CENTER_RESERVED_77', '')
CALL_CENTER_RESERVED_78 = os.getenv('CALL_CENTER_RESERVED_78', '')
CALL_CENTER_RESERVED_79 = os.getenv('CALL_CENTER_RESERVED_79', '')
CALL_CENTER_RESERVED_80 = os.getenv('CALL_CENTER_RESERVED_80', '')
CALL_CENTER_RESERVED_81 = os.getenv('CALL_CENTER_RESERVED_81', '')
CALL_CENTER_RESERVED_82 = os.getenv('CALL_CENTER_RESERVED_82', '')
CALL_CENTER_RESERVED_83 = os.getenv('CALL_CENTER_RESERVED_83', '')
CALL_CENTER_RESERVED_84 = os.getenv('CALL_CENTER_RESERVED_84', '')
CALL_CENTER_RESERVED_85 = os.getenv('CALL_CENTER_RESERVED_85', '')
CALL_CENTER_RESERVED_86 = os.getenv('CALL_CENTER_RESERVED_86', '')
CALL_CENTER_RESERVED_87 = os.getenv('CALL_CENTER_RESERVED_87', '')
CALL_CENTER_RESERVED_88 = os.getenv('CALL_CENTER_RESERVED_88', '')
CALL_CENTER_RESERVED_89 = os.getenv('CALL_CENTER_RESERVED_89', '')
CALL_CENTER_RESERVED_90 = os.getenv('CALL_CENTER_RESERVED_90', '')
CALL_CENTER_RESERVED_91 = os.getenv('CALL_CENTER_RESERVED_91', '')
CALL_CENTER_RESERVED_92 = os.getenv('CALL_CENTER_RESERVED_92', '')
CALL_CENTER_RESERVED_93 = os.getenv('CALL_CENTER_RESERVED_93', '')
CALL_CENTER_RESERVED_94 = os.getenv('CALL_CENTER_RESERVED_94', '')
CALL_CENTER_RESERVED_95 = os.getenv('CALL_CENTER_RESERVED_95', '')
CALL_CENTER_RESERVED_96 = os.getenv('CALL_CENTER_RESERVED_96', '')
CALL_CENTER_RESERVED_97 = os.getenv('CALL_CENTER_RESERVED_97', '')
CALL_CENTER_RESERVED_98 = os.getenv('CALL_CENTER_RESERVED_98', '')
CALL_CENTER_RESERVED_99 = os.getenv('CALL_CENTER_RESERVED_99', '')
CALL_CENTER_RESERVED_100 = os.getenv('CALL_CENTER_RESERVED_100', '')

# Meta / webhook hardening
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Call center webhook endpoints
CALL_CENTER_TWILIO_VOICE_PATH = '/enrollment/twilio/voice/'
CALL_CENTER_TWILIO_RECORDING_STATUS_PATH = '/enrollment/twilio/recording-status/'
CALL_CENTER_TWILIO_STATUS_CALLBACK_PATH = '/enrollment/twilio/status-callback/'
CALL_CENTER_META_WEBHOOK_PATH = '/enrollment/webhook/meta-lead/'

# Diagnostics
CALL_CENTER_DEBUG = os.getenv('CALL_CENTER_DEBUG', 'False') == 'True'
CALL_CENTER_VERBOSE_ERRORS = os.getenv('CALL_CENTER_VERBOSE_ERRORS', 'False') == 'True'

# Network / retries
CALL_CENTER_HTTP_TIMEOUT = int(os.getenv('CALL_CENTER_HTTP_TIMEOUT', '15'))
CALL_CENTER_HTTP_RETRY_COUNT = int(os.getenv('CALL_CENTER_HTTP_RETRY_COUNT', '2'))
CALL_CENTER_HTTP_RETRY_BACKOFF = float(os.getenv('CALL_CENTER_HTTP_RETRY_BACKOFF', '1.5'))

# Storage hooks (future)
CALL_CENTER_RECORDING_STORAGE = os.getenv('CALL_CENTER_RECORDING_STORAGE', 'twilio_url')  # twilio_url | s3 | local
CALL_CENTER_RECORDING_S3_BUCKET = os.getenv('CALL_CENTER_RECORDING_S3_BUCKET', '')
CALL_CENTER_RECORDING_S3_REGION = os.getenv('CALL_CENTER_RECORDING_S3_REGION', '')
CALL_CENTER_RECORDING_S3_PREFIX = os.getenv('CALL_CENTER_RECORDING_S3_PREFIX', 'call-recordings/')
CALL_CENTER_RECORDING_LOCAL_DIR = os.getenv('CALL_CENTER_RECORDING_LOCAL_DIR', '')

# Compliance / policy
CALL_CENTER_CONSENT_REQUIRED = os.getenv('CALL_CENTER_CONSENT_REQUIRED', 'False') == 'True'
CALL_CENTER_CONSENT_TEXT = os.getenv('CALL_CENTER_CONSENT_TEXT', "Suhbat sifati uchun qo'ng'iroq yozib olinadi")
CALL_CENTER_PRIVACY_MODE = os.getenv('CALL_CENTER_PRIVACY_MODE', 'False') == 'True'
CALL_CENTER_HIDE_RECORDING_URL_IN_UI = os.getenv('CALL_CENTER_HIDE_RECORDING_URL_IN_UI', 'False') == 'True'
CALL_CENTER_DELETE_RECORDING_ON_REQUEST = os.getenv('CALL_CENTER_DELETE_RECORDING_ON_REQUEST', 'False') == 'True'

# Outbound campaign defaults
CALL_CENTER_CAMPAIGN_DAILY_LIMIT = int(os.getenv('CALL_CENTER_CAMPAIGN_DAILY_LIMIT', '0'))
CALL_CENTER_CAMPAIGN_HOURLY_LIMIT = int(os.getenv('CALL_CENTER_CAMPAIGN_HOURLY_LIMIT', '0'))
CALL_CENTER_CAMPAIGN_ENABLE_AUTOPACING = os.getenv('CALL_CENTER_CAMPAIGN_ENABLE_AUTOPACING', 'False') == 'True'
CALL_CENTER_CAMPAIGN_AUTOPACING_RATE = float(os.getenv('CALL_CENTER_CAMPAIGN_AUTOPACING_RATE', '1.0'))

# Agent routing
CALL_CENTER_ROUTING_MODE = os.getenv('CALL_CENTER_ROUTING_MODE', 'single_number')  # single_number | round_robin | skill_based
CALL_CENTER_ROUND_ROBIN_STATE_KEY = os.getenv('CALL_CENTER_ROUND_ROBIN_STATE_KEY', 'call_center_rr_state')
CALL_CENTER_FALLBACK_AGENT_NUMBER = os.getenv('CALL_CENTER_FALLBACK_AGENT_NUMBER', '')

# Reserved config slots
CALL_CENTER_CFG_RESERVED_01 = os.getenv('CALL_CENTER_CFG_RESERVED_01', '')
CALL_CENTER_CFG_RESERVED_02 = os.getenv('CALL_CENTER_CFG_RESERVED_02', '')
CALL_CENTER_CFG_RESERVED_03 = os.getenv('CALL_CENTER_CFG_RESERVED_03', '')
CALL_CENTER_CFG_RESERVED_04 = os.getenv('CALL_CENTER_CFG_RESERVED_04', '')
CALL_CENTER_CFG_RESERVED_05 = os.getenv('CALL_CENTER_CFG_RESERVED_05', '')
CALL_CENTER_CFG_RESERVED_06 = os.getenv('CALL_CENTER_CFG_RESERVED_06', '')
CALL_CENTER_CFG_RESERVED_07 = os.getenv('CALL_CENTER_CFG_RESERVED_07', '')
CALL_CENTER_CFG_RESERVED_08 = os.getenv('CALL_CENTER_CFG_RESERVED_08', '')
CALL_CENTER_CFG_RESERVED_09 = os.getenv('CALL_CENTER_CFG_RESERVED_09', '')
CALL_CENTER_CFG_RESERVED_10 = os.getenv('CALL_CENTER_CFG_RESERVED_10', '')
CALL_CENTER_CFG_RESERVED_11 = os.getenv('CALL_CENTER_CFG_RESERVED_11', '')
CALL_CENTER_CFG_RESERVED_12 = os.getenv('CALL_CENTER_CFG_RESERVED_12', '')
CALL_CENTER_CFG_RESERVED_13 = os.getenv('CALL_CENTER_CFG_RESERVED_13', '')
CALL_CENTER_CFG_RESERVED_14 = os.getenv('CALL_CENTER_CFG_RESERVED_14', '')
CALL_CENTER_CFG_RESERVED_15 = os.getenv('CALL_CENTER_CFG_RESERVED_15', '')
CALL_CENTER_CFG_RESERVED_16 = os.getenv('CALL_CENTER_CFG_RESERVED_16', '')
CALL_CENTER_CFG_RESERVED_17 = os.getenv('CALL_CENTER_CFG_RESERVED_17', '')
CALL_CENTER_CFG_RESERVED_18 = os.getenv('CALL_CENTER_CFG_RESERVED_18', '')
CALL_CENTER_CFG_RESERVED_19 = os.getenv('CALL_CENTER_CFG_RESERVED_19', '')
CALL_CENTER_CFG_RESERVED_20 = os.getenv('CALL_CENTER_CFG_RESERVED_20', '')
CALL_CENTER_CFG_RESERVED_21 = os.getenv('CALL_CENTER_CFG_RESERVED_21', '')
CALL_CENTER_CFG_RESERVED_22 = os.getenv('CALL_CENTER_CFG_RESERVED_22', '')
CALL_CENTER_CFG_RESERVED_23 = os.getenv('CALL_CENTER_CFG_RESERVED_23', '')
CALL_CENTER_CFG_RESERVED_24 = os.getenv('CALL_CENTER_CFG_RESERVED_24', '')
CALL_CENTER_CFG_RESERVED_25 = os.getenv('CALL_CENTER_CFG_RESERVED_25', '')
CALL_CENTER_CFG_RESERVED_26 = os.getenv('CALL_CENTER_CFG_RESERVED_26', '')
CALL_CENTER_CFG_RESERVED_27 = os.getenv('CALL_CENTER_CFG_RESERVED_27', '')
CALL_CENTER_CFG_RESERVED_28 = os.getenv('CALL_CENTER_CFG_RESERVED_28', '')
CALL_CENTER_CFG_RESERVED_29 = os.getenv('CALL_CENTER_CFG_RESERVED_29', '')
CALL_CENTER_CFG_RESERVED_30 = os.getenv('CALL_CENTER_CFG_RESERVED_30', '')
CALL_CENTER_CFG_RESERVED_31 = os.getenv('CALL_CENTER_CFG_RESERVED_31', '')
CALL_CENTER_CFG_RESERVED_32 = os.getenv('CALL_CENTER_CFG_RESERVED_32', '')
CALL_CENTER_CFG_RESERVED_33 = os.getenv('CALL_CENTER_CFG_RESERVED_33', '')
CALL_CENTER_CFG_RESERVED_34 = os.getenv('CALL_CENTER_CFG_RESERVED_34', '')
CALL_CENTER_CFG_RESERVED_35 = os.getenv('CALL_CENTER_CFG_RESERVED_35', '')
CALL_CENTER_CFG_RESERVED_36 = os.getenv('CALL_CENTER_CFG_RESERVED_36', '')
CALL_CENTER_CFG_RESERVED_37 = os.getenv('CALL_CENTER_CFG_RESERVED_37', '')
CALL_CENTER_CFG_RESERVED_38 = os.getenv('CALL_CENTER_CFG_RESERVED_38', '')
CALL_CENTER_CFG_RESERVED_39 = os.getenv('CALL_CENTER_CFG_RESERVED_39', '')
CALL_CENTER_CFG_RESERVED_40 = os.getenv('CALL_CENTER_CFG_RESERVED_40', '')
CALL_CENTER_CFG_RESERVED_41 = os.getenv('CALL_CENTER_CFG_RESERVED_41', '')
CALL_CENTER_CFG_RESERVED_42 = os.getenv('CALL_CENTER_CFG_RESERVED_42', '')
CALL_CENTER_CFG_RESERVED_43 = os.getenv('CALL_CENTER_CFG_RESERVED_43', '')
CALL_CENTER_CFG_RESERVED_44 = os.getenv('CALL_CENTER_CFG_RESERVED_44', '')
CALL_CENTER_CFG_RESERVED_45 = os.getenv('CALL_CENTER_CFG_RESERVED_45', '')
CALL_CENTER_CFG_RESERVED_46 = os.getenv('CALL_CENTER_CFG_RESERVED_46', '')
CALL_CENTER_CFG_RESERVED_47 = os.getenv('CALL_CENTER_CFG_RESERVED_47', '')
CALL_CENTER_CFG_RESERVED_48 = os.getenv('CALL_CENTER_CFG_RESERVED_48', '')
CALL_CENTER_CFG_RESERVED_49 = os.getenv('CALL_CENTER_CFG_RESERVED_49', '')
CALL_CENTER_CFG_RESERVED_50 = os.getenv('CALL_CENTER_CFG_RESERVED_50', '')
CALL_CENTER_CFG_RESERVED_51 = os.getenv('CALL_CENTER_CFG_RESERVED_51', '')
CALL_CENTER_CFG_RESERVED_52 = os.getenv('CALL_CENTER_CFG_RESERVED_52', '')
CALL_CENTER_CFG_RESERVED_53 = os.getenv('CALL_CENTER_CFG_RESERVED_53', '')
CALL_CENTER_CFG_RESERVED_54 = os.getenv('CALL_CENTER_CFG_RESERVED_54', '')
CALL_CENTER_CFG_RESERVED_55 = os.getenv('CALL_CENTER_CFG_RESERVED_55', '')
CALL_CENTER_CFG_RESERVED_56 = os.getenv('CALL_CENTER_CFG_RESERVED_56', '')
CALL_CENTER_CFG_RESERVED_57 = os.getenv('CALL_CENTER_CFG_RESERVED_57', '')
CALL_CENTER_CFG_RESERVED_58 = os.getenv('CALL_CENTER_CFG_RESERVED_58', '')
CALL_CENTER_CFG_RESERVED_59 = os.getenv('CALL_CENTER_CFG_RESERVED_59', '')
CALL_CENTER_CFG_RESERVED_60 = os.getenv('CALL_CENTER_CFG_RESERVED_60', '')
CALL_CENTER_CFG_RESERVED_61 = os.getenv('CALL_CENTER_CFG_RESERVED_61', '')
CALL_CENTER_CFG_RESERVED_62 = os.getenv('CALL_CENTER_CFG_RESERVED_62', '')
CALL_CENTER_CFG_RESERVED_63 = os.getenv('CALL_CENTER_CFG_RESERVED_63', '')
CALL_CENTER_CFG_RESERVED_64 = os.getenv('CALL_CENTER_CFG_RESERVED_64', '')
CALL_CENTER_CFG_RESERVED_65 = os.getenv('CALL_CENTER_CFG_RESERVED_65', '')
CALL_CENTER_CFG_RESERVED_66 = os.getenv('CALL_CENTER_CFG_RESERVED_66', '')
CALL_CENTER_CFG_RESERVED_67 = os.getenv('CALL_CENTER_CFG_RESERVED_67', '')
CALL_CENTER_CFG_RESERVED_68 = os.getenv('CALL_CENTER_CFG_RESERVED_68', '')
CALL_CENTER_CFG_RESERVED_69 = os.getenv('CALL_CENTER_CFG_RESERVED_69', '')
CALL_CENTER_CFG_RESERVED_70 = os.getenv('CALL_CENTER_CFG_RESERVED_70', '')
CALL_CENTER_CFG_RESERVED_71 = os.getenv('CALL_CENTER_CFG_RESERVED_71', '')
CALL_CENTER_CFG_RESERVED_72 = os.getenv('CALL_CENTER_CFG_RESERVED_72', '')
CALL_CENTER_CFG_RESERVED_73 = os.getenv('CALL_CENTER_CFG_RESERVED_73', '')
CALL_CENTER_CFG_RESERVED_74 = os.getenv('CALL_CENTER_CFG_RESERVED_74', '')
CALL_CENTER_CFG_RESERVED_75 = os.getenv('CALL_CENTER_CFG_RESERVED_75', '')
CALL_CENTER_CFG_RESERVED_76 = os.getenv('CALL_CENTER_CFG_RESERVED_76', '')
CALL_CENTER_CFG_RESERVED_77 = os.getenv('CALL_CENTER_CFG_RESERVED_77', '')
CALL_CENTER_CFG_RESERVED_78 = os.getenv('CALL_CENTER_CFG_RESERVED_78', '')
CALL_CENTER_CFG_RESERVED_79 = os.getenv('CALL_CENTER_CFG_RESERVED_79', '')
CALL_CENTER_CFG_RESERVED_80 = os.getenv('CALL_CENTER_CFG_RESERVED_80', '')
CALL_CENTER_CFG_RESERVED_81 = os.getenv('CALL_CENTER_CFG_RESERVED_81', '')
CALL_CENTER_CFG_RESERVED_82 = os.getenv('CALL_CENTER_CFG_RESERVED_82', '')
CALL_CENTER_CFG_RESERVED_83 = os.getenv('CALL_CENTER_CFG_RESERVED_83', '')
CALL_CENTER_CFG_RESERVED_84 = os.getenv('CALL_CENTER_CFG_RESERVED_84', '')
CALL_CENTER_CFG_RESERVED_85 = os.getenv('CALL_CENTER_CFG_RESERVED_85', '')
CALL_CENTER_CFG_RESERVED_86 = os.getenv('CALL_CENTER_CFG_RESERVED_86', '')
CALL_CENTER_CFG_RESERVED_87 = os.getenv('CALL_CENTER_CFG_RESERVED_87', '')
CALL_CENTER_CFG_RESERVED_88 = os.getenv('CALL_CENTER_CFG_RESERVED_88', '')
CALL_CENTER_CFG_RESERVED_89 = os.getenv('CALL_CENTER_CFG_RESERVED_89', '')
CALL_CENTER_CFG_RESERVED_90 = os.getenv('CALL_CENTER_CFG_RESERVED_90', '')
CALL_CENTER_CFG_RESERVED_91 = os.getenv('CALL_CENTER_CFG_RESERVED_91', '')
CALL_CENTER_CFG_RESERVED_92 = os.getenv('CALL_CENTER_CFG_RESERVED_92', '')
CALL_CENTER_CFG_RESERVED_93 = os.getenv('CALL_CENTER_CFG_RESERVED_93', '')
CALL_CENTER_CFG_RESERVED_94 = os.getenv('CALL_CENTER_CFG_RESERVED_94', '')
CALL_CENTER_CFG_RESERVED_95 = os.getenv('CALL_CENTER_CFG_RESERVED_95', '')
CALL_CENTER_CFG_RESERVED_96 = os.getenv('CALL_CENTER_CFG_RESERVED_96', '')
CALL_CENTER_CFG_RESERVED_97 = os.getenv('CALL_CENTER_CFG_RESERVED_97', '')
CALL_CENTER_CFG_RESERVED_98 = os.getenv('CALL_CENTER_CFG_RESERVED_98', '')
CALL_CENTER_CFG_RESERVED_99 = os.getenv('CALL_CENTER_CFG_RESERVED_99', '')
CALL_CENTER_CFG_RESERVED_100 = os.getenv('CALL_CENTER_CFG_RESERVED_100', '')

# End of integration configs
TWILIO_EDGE = os.getenv('TWILIO_EDGE', '')
TWILIO_REGION = os.getenv('TWILIO_REGION', '')
TWILIO_TIMEOUT = int(os.getenv('TWILIO_TIMEOUT', '10'))
TWILIO_VALIDATE_REQUEST = os.getenv('TWILIO_VALIDATE_REQUEST', 'False') == 'True'
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')

# Default application identity
APP_BRAND_NAME = os.getenv('APP_BRAND_NAME', 'Bunyod Non Sharjah School')
APP_ORG_TYPE = os.getenv('APP_ORG_TYPE', 'private_school')
APP_ADMISSIONS_ENABLED = os.getenv('APP_ADMISSIONS_ENABLED', 'True') == 'True'
APP_CALL_CENTER_ENABLED = os.getenv('APP_CALL_CENTER_ENABLED', 'True') == 'True'  # noqa: E501

# Backward compatibility for existing code paths
LOGIN_REDIRECT_URL = '/'

# NOTE: все параметры выше безопасны, пока реальные секреты задаются только через ENV.

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Channels configuration (commented — requires channels + redis)
# ASGI_APPLICATION = 'bakery_erp.asgi.application'
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', 6379)))],
#         },
#     },
# }

# Django REST Framework (commented — requires djangorestframework)
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 25,
# }

# CORS settings (commented — requires django-cors-headers)
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:8000',
#     'http://127.0.0.1:8000',
# ]
# CORS_ALLOW_CREDENTIALS = True

# Celery configuration
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST', '127.0.0.1')}:{os.getenv('REDIS_PORT', 6379)}/0"
CELERY_RESULT_BACKEND = f"redis://{os.getenv('REDIS_HOST', '127.0.0.1')}:{os.getenv('REDIS_PORT', 6379)}/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tashkent'

# Call Centre specific settings
CALL_RECORDING_STORAGE = os.getenv('CALL_RECORDING_STORAGE', 'local')  # local, s3
CALL_RECORDING_CONSENT_REQUIRED = os.getenv('CALL_RECORDING_CONSENT_REQUIRED', 'True') == 'True'
CALL_MAX_DURATION_SECONDS = int(os.getenv('CALL_MAX_DURATION_SECONDS', '3600'))
CALL_QUEUE_MAX_WAIT_SECONDS = int(os.getenv('CALL_QUEUE_MAX_WAIT_SECONDS', '300'))

# AWS S3 for call recordings (optional)
if CALL_RECORDING_STORAGE == 's3':
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = 'private'
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600
