# Generated by Django 6.0.4 on 2026-05-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_documenttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=True, help_text="Online to'lovlar uchun tasdiqlash holati"),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text="Online to'lov tranzaksiya ID", max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum Bank'), ('apelsin', 'Apelsin'), ('humo', 'Humo'), ('uzcard', 'UzCard'), ('online', "Online to'lov")], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum Bank'), ('apelsin', 'Apelsin'), ('humo', 'Humo'), ('uzcard', 'UzCard')], max_length=20)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('order_id', models.CharField(blank=True, help_text='Tizim ichki order ID', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('failed', 'Xato'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarildi')], default='pending', max_length=20)),
                ('month_for', models.DateField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payments', to='students.contract')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payment', to='students.payment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
