# Generated by Django 6.0.4 on 2026-05-13 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_payment_is_confirmed_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'period__lesson_number', 'start_time']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, help_text='Xona raqami', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LessonPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('primary', "Boshlang'ich (1-4 sinf)"), ('secondary', "O'rta (5-9 sinf)"), ('high', 'Yuqori (10-11 sinf)')], max_length=20)),
                ('lesson_number', models.IntegerField(help_text='1-soat, 2-soat...')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, help_text='Masalan: 1-dars, Tanaffus', max_length=50)),
            ],
            options={
                'ordering': ['level', 'lesson_number'],
                'unique_together': {('level', 'lesson_number')},
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='students.lessonperiod'),
        ),
    ]
