# Generated by Django 6.0.4 on 2026-05-13 04:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(default='secondary', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_mode', models.CharField(choices=[('round_robin', 'Round Robin (avtomatik)'), ('manual', "Qo'lda (admin tomonidan)")], default='round_robin', max_length=20)),
                ('round_robin_index', models.IntegerField(default=0)),
                ('meta_verify_token', models.CharField(blank=True, max_length=200)),
                ('meta_access_token', models.CharField(blank=True, max_length=500)),
                ('meta_app_secret', models.CharField(blank=True, max_length=200)),
                ('meta_page_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='MetaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_uuid', models.CharField(blank=True, max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('phone_number2', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('product_interest', models.CharField(blank=True, max_length=200)),
                ('campaign_name', models.CharField(blank=True, max_length=200)),
                ('adset_name', models.CharField(blank=True, max_length=200)),
                ('form_name', models.CharField(blank=True, max_length=200)),
                ('meta_created_time', models.DateTimeField(blank=True, null=True)),
                ('crm_received_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('callback_date', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('current_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='callcenter.leadstatus')),
            ],
            options={
                'ordering': ['-crm_received_time'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='callcenter.leadstatus')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='callcenter.leadstatus')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_status_history', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='callcenter.metalead')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_comments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='callcenter.metalead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_datetime', models.DateTimeField()),
                ('callback_note', models.TextField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='callcenter.metalead')),
            ],
            options={
                'ordering': ['callback_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_lead', 'Yangi lead'), ('callback_due', 'Callback vaqti'), ('untouched', "Tegib ko'rilmagan"), ('reminder', 'Eslatma')], default='reminder', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callcenter.metalead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
