# Generated by Django 6.0.4 on 2026-05-03 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0003_alter_finishedgoodsinventory_id_alter_product_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="finishedgoodsinventory",
            name="produced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="batches",
            field=models.IntegerField(default=1, help_text="Number of recipe batches"),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="timer_minutes",
            field=models.IntegerField(
                default=0, help_text="Production timer in minutes"
            ),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="timer_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipeitem",
            name="quantity_grams",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Optional gram equivalent if unit is kg",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productionlog",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="stock",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="batch_size",
            field=models.IntegerField(help_text="Quantity produced by this recipe"),
        ),
        migrations.AlterField(
            model_name="recipeitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Amount in raw_material's unit",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="production.productcategory",
            ),
        ),
    ]
