# Generated by Django 6.0.4 on 2026-05-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0004_productcategory_finishedgoodsinventory_produced_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDayBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance_date", models.DateField(db_index=True)),
                (
                    "opening_qty",
                    models.IntegerField(
                        default=0,
                        help_text="Kun boshidagi qoldiq (oldingi kun closing yoki carried-forward)",
                    ),
                ),
                (
                    "closing_qty",
                    models.IntegerField(
                        blank=True, help_text="Kun yakunidagi fizik qoldiq", null=True
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_balances",
                        to="production.product",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("balance_date", "product"),
                        name="uniq_product_day_balance",
                    )
                ],
            },
        ),
    ]
