# Generated by Django 6.0.4 on 2026-05-03 09:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_shift_employee_daily_target_employee_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="hours_absent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kelmagan vaqt",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="hours_expected",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("8"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="hours_left_early",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Erta ketgan vaqt",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="hours_present",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="was_present",
            field=models.BooleanField(
                default=True, help_text="False bo'lsa — kelmagan kun"
            ),
        ),
    ]
