# Generated by Django 6.0.4 on 2026-05-03 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_shift_alloc_and_daily_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="units_from_sales",
            field=models.IntegerField(
                default=0,
                help_text="Sotuvdan avtomatik yozilgan donalar (bog'langan sotuvchi hisobi bilan)",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user_account",
            field=models.OneToOneField(
                blank=True,
                help_text="Sotuv panelidagi foydalanuvchi bilan bog'lash (ishbay avtomatik yozuvlari uchun)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="units_produced",
            field=models.IntegerField(
                default=0, help_text="Qo'lda kiritilgan nagruzka / ishlab chiqarish"
            ),
        ),
    ]
