# Generated by Django 6.0.4 on 2026-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_piecework_user_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
