# Generated by Django 6.0.4 on 2026-05-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_add_position_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="absence_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("sick", "Kasal"),
                    ("personal", "Shaxsiy masala"),
                    ("approved", "Sababli (tasdiqlangan)"),
                    ("no_reason", "Sababsiz"),
                ],
                default="",
                help_text="Kelmagan sababi",
                max_length=20,
            ),
        ),
    ]
