# Generated by Django 6.0.4 on 2026-05-12 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="LeadSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., meta, web, phone, referral",
                        max_length=30,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, help_text="Ichki raqam", max_length=10
                    ),
                ),
                (
                    "twilio_worker_sid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("max_concurrent_calls", models.IntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("active", "Faol"),
                            ("completed", "Yakunlandi"),
                            ("paused", "To'xtatildi"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "child_name",
                    models.CharField(
                        blank=True, help_text="Bolaning ismi", max_length=200
                    ),
                ),
                (
                    "child_age",
                    models.IntegerField(
                        blank=True, help_text="Bolaning yoshi", null=True
                    ),
                ),
                (
                    "meta_lead_id",
                    models.CharField(
                        blank=True,
                        help_text="Meta Lead ID (Facebook/Instagram)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("contacted", "Bog'lanildi"),
                            ("interested", "Qiziqish bor"),
                            ("appointment", "Uchrashuv belgilangan"),
                            ("registered", "Ro'yxatdan o'tdi"),
                            ("declined", "Rad etildi"),
                            ("not_reachable", "Bog'lanib bo'lmadi"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interested_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="enrollment.grade",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="enrollment.leadsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caller_number",
                    models.CharField(
                        help_text="Qo'ng'iroq qilgan raqam", max_length=30
                    ),
                ),
                (
                    "callee_number",
                    models.CharField(help_text="Qabul qiluvchi raqam", max_length=30),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Kiruvchi"), ("outbound", "Chiquvchi")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ringing", "Qo'ng'iroq qilinmoqda"),
                            ("in_progress", "Gaplashmoqda"),
                            ("completed", "Yakunlandi"),
                            ("missed", "Javob berilmadi"),
                            ("voicemail", "Ovozli xabar"),
                            ("failed", "Muvaffaqiyatsiz"),
                        ],
                        default="ringing",
                        max_length=20,
                    ),
                ),
                (
                    "twilio_call_sid",
                    models.CharField(
                        blank=True,
                        help_text="Twilio Call SID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(
                        blank=True, help_text="Yozib olingan audio URL", null=True
                    ),
                ),
                (
                    "recording_sid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="enrollment.callcampaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="enrollment.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_first_name", models.CharField(max_length=100)),
                ("parent_last_name", models.CharField(max_length=100)),
                ("parent_phone", models.CharField(max_length=30)),
                (
                    "parent_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "parent_relation",
                    models.CharField(
                        default="Ota", help_text="Ota, Ona, Vasiy...", max_length=50
                    ),
                ),
                ("student_first_name", models.CharField(max_length=100)),
                ("student_last_name", models.CharField(max_length=100)),
                ("student_dob", models.DateField(help_text="Tug'ilgan sana")),
                (
                    "student_gender",
                    models.CharField(
                        choices=[("M", "O'g'il"), ("F", "Qiz")], max_length=1
                    ),
                ),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                (
                    "medical_notes",
                    models.TextField(blank=True, help_text="Tibbiy eslatmalar"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("submitted", "Topshirildi"),
                            ("under_review", "Ko'rib chiqilmoqda"),
                            ("documents_pending", "Hujjatlar kutilmoqda"),
                            ("assessment", "Sinov"),
                            ("approved", "Qabul qilindi"),
                            ("enrolled", "Ro'yxatdan o'tdi"),
                            ("rejected", "Rad etildi"),
                            ("waitlisted", "Kutish ro'yxati"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("application_fee_paid", models.BooleanField(default=False)),
                (
                    "application_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applying_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="enrollment.grade",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="enrollment.lead",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
