# Generated by Django 6.0.4 on 2026-05-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="children_count",
            field=models.IntegerField(default=1, help_text="Bolalar soni"),
        ),
        migrations.AddField(
            model_name="lead",
            name="discount_info",
            field=models.CharField(
                blank=True, help_text="Chegirma ma'lumoti", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_ad_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_adset_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_adset_name",
            field=models.CharField(
                blank=True, help_text="Meta reklama to'plami", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_campaign_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_campaign_name",
            field=models.CharField(
                blank=True, help_text="Meta kampaniya nomi", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_form_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_form_name",
            field=models.CharField(
                blank=True, help_text="Meta forma nomi", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone_2",
            field=models.CharField(
                blank=True, help_text="Ikkinchi telefon raqami", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="region",
            field=models.CharField(
                blank=True, help_text="Viloyat/Shahar", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="LeadComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="enrollment.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="enrollment.lead",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lead Status Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
