# Generated by Django 6.0.4 on 2026-05-12 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0002_lead_children_count_lead_discount_info_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("call_initiated", "Qo'ng'iroq boshlandi"),
                            ("call_answered", "Qo'ng'iroqga javob berildi"),
                            ("call_ended", "Qo'ng'iroq tugadi"),
                            ("recording_started", "Yozuv boshlandi"),
                            ("recording_stopped", "Yozuv to'xtatildi"),
                            ("recording_accessed", "Yozuvga kirish"),
                            ("recording_deleted", "Yozuv o'chirildi"),
                            ("agent_status_changed", "Agent holati o'zgartirildi"),
                            ("lead_created", "Lead yaratildi"),
                            ("lead_updated", "Lead yangilandi"),
                            ("settings_changed", "Sozlamalar o'zgartirildi"),
                            ("user_login", "Foydalanuvchi kirdi"),
                            ("user_logout", "Foydalanuvchi chiqdi"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=100)),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_name", models.CharField(default="default", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Kutmoqda"),
                            ("assigned", "Tayinlangan"),
                            ("answered", "Javob berildi"),
                            ("abandoned", "Tashlab ketildi"),
                            ("timeout", "Vaqt tugadi"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Yuqori raqam = yuqori ustuvorlik"
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("wait_time_seconds", models.IntegerField(default=0)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-priority", "entered_at"],
            },
        ),
        migrations.CreateModel(
            name="CallRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Asosiy raqam", max_length=30, unique=True
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("round_robin", "Round Robin"),
                            ("least_busy", "Eng kam yuklangan"),
                            ("longest_idle", "Eng uzoq bo'sh"),
                            ("skill_based", "Malaka asosida"),
                            ("priority", "Ustuvorlik asosida"),
                        ],
                        default="round_robin",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("business_hours_only", models.BooleanField(default=False)),
                ("business_hours_start", models.TimeField(default="09:00")),
                ("business_hours_end", models.TimeField(default="18:00")),
                ("max_queue_size", models.IntegerField(default=50)),
                ("max_wait_time_seconds", models.IntegerField(default=300)),
                (
                    "overflow_number",
                    models.CharField(
                        blank=True,
                        help_text="Navbat to'lganda yo'naltirish",
                        max_length=30,
                    ),
                ),
                ("welcome_message", models.TextField(blank=True)),
                ("queue_music_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CallStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_calls", models.IntegerField(default=0)),
                ("inbound_calls", models.IntegerField(default=0)),
                ("outbound_calls", models.IntegerField(default=0)),
                ("answered_calls", models.IntegerField(default=0)),
                ("missed_calls", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                ("total_talk_time_seconds", models.IntegerField(default=0)),
                ("total_wait_time_seconds", models.IntegerField(default=0)),
                ("avg_duration_seconds", models.FloatField(default=0)),
                ("avg_wait_time_seconds", models.FloatField(default=0)),
                ("recordings_count", models.IntegerField(default=0)),
                ("recordings_with_consent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="last_call_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Operator telefon raqami", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("busy", "Zan"),
                    ("break", "Tanaffus"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="total_calls_handled",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="disposition",
            field=models.CharField(
                blank=True, help_text="Qo'ng'iroq natijasi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="is_flagged",
            field=models.BooleanField(default=False, help_text="Muammo belgisi"),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="quality_score",
            field=models.IntegerField(blank=True, help_text="1-5 ball", null=True),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="recording_consent",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("accepted", "Qabul qilindi"),
                    ("declined", "Rad etildi"),
                    ("not_asked", "So'ralmadi"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="recording_consent_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="recording_duration",
            field=models.IntegerField(
                blank=True, help_text="Yozuv davomiyligi (soniya)", null=True
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="recording_file",
            field=models.FileField(
                blank=True, null=True, upload_to="call_recordings/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_calls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Vergul bilan ajratilgan teglar", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="talk_time_seconds",
            field=models.IntegerField(
                blank=True, help_text="Gaplashish vaqti", null=True
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="twilio_conference_sid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="wait_time_seconds",
            field=models.IntegerField(blank=True, help_text="Kutish vaqti", null=True),
        ),
        migrations.AlterField(
            model_name="callrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("ringing", "Qo'ng'iroq qilinmoqda"),
                    ("in_progress", "Gaplashmoqda"),
                    ("completed", "Yakunlandi"),
                    ("missed", "Javob berilmadi"),
                    ("voicemail", "Ovozli xabar"),
                    ("failed", "Muvaffaqiyatsiz"),
                    ("no_answer", "Javob yo'q"),
                    ("busy", "Zan"),
                ],
                default="ringing",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["-created_at"], name="enrollment__created_3a598c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["agent", "-created_at"], name="enrollment__agent_i_adbc10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["lead", "-created_at"], name="enrollment__lead_id_1b5d07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(fields=["status"], name="enrollment__status_0c8af7_idx"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callqueue",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callqueue",
            name="call",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_entry",
                to="enrollment.callrecord",
            ),
        ),
        migrations.AddField(
            model_name="callstatistics",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at"], name="enrollment__created_5533f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="enrollment__user_id_2caecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-created_at"], name="enrollment__action_3cec82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callqueue",
            index=models.Index(
                fields=["status", "-priority", "entered_at"],
                name="enrollment__status_1424b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callstatistics",
            index=models.Index(fields=["-date"], name="enrollment__date_a2fd27_idx"),
        ),
        migrations.AddIndex(
            model_name="callstatistics",
            index=models.Index(
                fields=["agent", "-date"], name="enrollment__agent_i_470c1a_idx"
            ),
        ),
    ]
