# Generated by Django 6.0.4 on 2026-05-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_account_id_alter_cashregister_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("payme", "Payme"),
                            ("payme_business", "Payme Business"),
                            ("click", "Click"),
                            ("uzum", "Uzum Bank"),
                            ("apelsin", "Apelsin"),
                            ("humo", "Humo"),
                            ("uzcard", "UzCard"),
                            ("multicard", "Multicard"),
                            ("anorbank", "Anorbank"),
                            ("alif", "Alif Mobi"),
                            ("cap", "CAP"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("merchant_id", models.CharField(blank=True, max_length=200)),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("api_url", models.CharField(blank=True, max_length=300)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_test", models.BooleanField(default=True, help_text="Test rejimi")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["provider"],
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cashregister",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="journalline",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
