# Generated by Django 6.0.4 on 2026-05-03 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_returnlog_id_alter_sale_id_alter_saleitem_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="shift_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="returnlog",
            name="reason",
            field=models.CharField(
                choices=[("brak", "Brak"), ("unsold", "Sotilmagan")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Naqd"),
                    ("terminal", "Terminal"),
                    ("electronic", "Click/Payme"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
