# Generated by Django 6.0.4 on 2026-05-03 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0004_productcategory_finishedgoodsinventory_produced_at_and_more",
        ),
        ("sales", "0004_sale_seller_sale_shift_name_alter_returnlog_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("shift_name", models.CharField(max_length=100)),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_closures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "shift_name"),
                        name="uniq_sales_shift_day_closure",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftDailyAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("shift_name", models.CharField(max_length=100)),
                ("allocated_qty", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_allocations",
                        to="production.product",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "shift_name", "product"),
                        name="uniq_sales_shift_day_product_alloc",
                    )
                ],
            },
        ),
    ]
